# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
project_id = "enclave-messaging-api"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 55433
major_version = 17

[functions.exchange-account-token]
enabled = true
verify_jwt = false
entrypoint = "./functions/exchange-account-token/index.ts"

[functions.livekit-token]
enabled = true
verify_jwt = true
entrypoint = "./functions/livekit-token/index.ts"

[functions.send-message-notification]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-message-notification/index.ts"

[functions.delete-account-cleanup]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete-account-cleanup/index.ts"
